from __future__ import annotations

FULL_WORKFLOW_MESSAGES = {
    "hi": {
        "department_booking_prompt": "{department} डॉक्टर के साथ अपॉइंटमेंट बुक करना चाहेंगे? ({yes} / {no})",
        "booking_prompt": "क्या मैं आपके लिए उपलब्ध अपॉइंटमेंट स्लॉट ढूंढूं? ({yes} / {no})",
        "report_forward_prompt": "क्या मैं आपकी विस्तृत चिकित्सा रिपोर्ट {doctor} को अपॉइंटमेंट से पहले भेजूं? इसमें हमारे द्वारा चर्चा की गई लक्षण, पैटर्न, ट्रिगर और अनुशंसाएं शामिल होंगी। ({yes} / {no})",
        "appointment_confirmed": "{doctor} के साथ आपकी अपॉइंटमेंट {date_time} के लिए सुनिश्चित कर दी गई है। संदर्भ आईडी: {reference}।",
        "report_sent": "आपकी चिकित्सा रिपोर्ट {doctor} को भेज दी गई है।",
        "cancellation_prompt": "क्या आप {date_time} को {doctor} के साथ अपनी अपॉइंटमेंट रद्द करना चाहेंगे? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} के साथ आपकी अपॉइंटमेंट {date_time} पर रद्द कर दी गई है।",
        "reschedule_prompt": "क्या आप {doctor} के साथ अपनी अपॉइंटमेंट पुनर्निर्धारित करना चाहेंगे? ({yes} / {no})",
        "slot_error": "वह अपॉइंटमेंट स्लॉट अब उपलब्ध नहीं है। कृपया कोई अन्य स्लॉट चुनें।",
        "selection_error": "मैं उस चयन को समझ नहीं सका। कृपया प्रदर्शित विकल्पों में से एक चुनें।"
    },
    "te": {
        "department_booking_prompt": "{department} డాక్టర్ తో ఒక అపాయింట్మెంట్ బుక్ చెయ్యాలా? ({yes} / {no})",
        "booking_prompt": "మీ కోసం అందుబాటులో ఉన్న అపాయింట్మెంట్ స్లాట్‌లు కనుగొనమా? ({yes} / {no})",
        "report_forward_prompt": "మీ అపాయింట్మెంట్ ముందు మీ వివరణాత్మక నివేదికను {doctor} కి పంపాలా? ఇది మేము చర్చించిన లక్షణాలు, నమూనాలు, ట్రిగ్గర్లు మరియు సిఫారసులను ఉంటుంది. ({yes} / {no})",
        "appointment_confirmed": "{doctor} తో మీ అపాయింట్మెంట్ {date_time}కి నిర్ధారించబడింది. సూచనా ఐడి: {reference}.",
        "report_sent": "మీ నివేదిక {doctor} కు పంపబడింది.",
        "cancellation_prompt": "{date_time} న {doctor} తో మీ అపాయింట్మెంట్ ని రద్దు చేసుకోవాలా? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} తో మీ అపాయింట్మెంట్ {date_time} న రద్దు చేయబడింది.",
        "reschedule_prompt": "{doctor} తో మీ అపాయింట్మెంట్ ను రీషెడ్యూల్ చేయవలసిందిగా కోరుకుంటున్నారా? ({yes} / {no})",
        "slot_error": "ఆ అపాయింట్మెంట్ స్లాట్ ఇప్పుడు అందుబాటులో లేదు. దయచేసి మరొక స్లాట్ ఎంచుకోండి.",
        "selection_error": "ఆ ఎంపికను నేను అర్థం చేసుకోలేదు. దయచేసి ప్రదర్శించిన ఎంపికలలో ఒకటి ఎంచుకోండి."
    },
    "ta": {
        "department_booking_prompt": "{department} மருத்துவரின் நேர்முகப் பேட்டியைச் சரிசெய்ய விரும்புகிறீர்களா? ({yes} / {no})",
        "booking_prompt": "உங்களுக்கு கிடைக்கக்கூடிய நேர்முக நேரங்களை நான் கண்டறியவா? ({yes} / {no})",
        "report_forward_prompt": "உங்களுடைய விரிவான மருத்துவ அறிக்கையை {doctor}க்கு உங்கள் நேர்முகத்திற்கு முன் அனுப்பவா? இதனால் நாம் விவாதித்த அறிகுறிகள், வடிவங்கள், தூண்டுதல்கள் மற்றும் பரிந்துரைகள் உள்ளடக்கப்படும். ({yes} / {no})",
        "appointment_confirmed": "{doctor} உடன் உங்கள் நேர்முக நேரம் {date_time}க்கு உறுதி செய்யப்பட்டது. குறிப்பு ID: {reference}.",
        "report_sent": "உங்கள் மருத்துவ அறிக்கை {doctor} க்கு அனுப்பப்பட்டது.",
        "cancellation_prompt": "{doctor} உடன் {date_time}க்கு உங்கள் நேர்முகத்தை ரத்து செய்ய விரும்புகிறீர்களா? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} உடன் {date_time} அழைக்கப்பட்ட நேர்முகம் ரத்து செய்யப்பட்டது.",
        "reschedule_prompt": "{doctor} உடன் உங்கள் நேர்முகத்தை மீண்டும் அட்டவணைப்படுத்த விரும்புகிறீர்களா? ({yes} / {no})",
        "slot_error": "இந்த நேர்முக இடைவெளி இனி கிடைக்காது. தயவுசெய்து மற்றொரு இடைவெளிக்குக் காண்கவும்.",
        "selection_error": "அந்த தேர்வை நான் புரிந்துகொள்ள முடியவில்லை. தயவுசெய்து எந்த நிலைமைகளை காட்டு என்று பார்த்துக் கொள்ளுங்கள்."
    },
    "kn": {
        "department_booking_prompt": "{department} ವೈದ್ಯರೊಂದಿಗೆ ಭೇಟಿಯನ್ನು ಬುಕ್ಅಪ್ ಮಾಡುವುದು ಬಯಸುತ್ತೀರಾ? ({yes} / {no})",
        "booking_prompt": "ನಾನು ನಿಮಗೆ ಲಭ್ಯವಿರುವ ಭೇಟಿರೂಪದ ಸ್ಥಾನಗಳನ್ನು ಹುಡುಕಲು ಬಯಸುತ್ತೀನಿ? ({yes} / {no})",
        "report_forward_prompt": "{doctor} ಗೆ ನಿಮ್ಮ विस्तೃತ ವೈದ್ಯಕೀಯ ವರದಿಯನ್ನು ಭೇಟಿಗೆ ಮುಂಚೆ ಕಳುಹಿಸಿಕೊಂಡುಕೊಳ್ಳಲು ಇದೆಯೆ? ಇದು ನಾವು ಚರ್ಚಿಸಿದ ಲಕ್ಷಣಗಳನ್ನು, ಮಾದರಿಗಳನ್ನು, ಕಾರ್ಪೊರೇಷನ್‌ಗಳನ್ನು ಒಳಗೊಂಡಿರುತ್ತದೆ. ({yes} / {no})",
        "appointment_confirmed": "{doctor} ಜೊತೆ ನಿಮ್ಮ ಭೇಟಿಯು {date_time} ಆಧಾರಿತವಾಗಿದೆ. ಸೂಚನೆ ID: {reference}.",
        "report_sent": "ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ವರದಿ {doctor} ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
        "cancellation_prompt": "{doctor} ಜೊತೆ {date_time} ನಲ್ಲಿ ನಿಮ್ಮ ಭೇಟಿಯನ್ನು ರದ್ದುಪಡಿಸಬೇಕೆಂದು ಬಯಸುತ್ತೀರಾ? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} ಜೊತೆ {date_time} ವೇಳೆ ನಿಮ್ಮ ಭೇಟಿಯನ್ನು ರದ್ದುಪಡಿಸಲಾಗಿದೆ.",
        "reschedule_prompt": "{doctor} ಜೊತೆ ನಿಮ್ಮ ಭೇಟಿಯನ್ನು ಪುನಃ ಯೋಜನೆ ಮಾಡಬೇಕೆಂದು ಬಯಸುತ್ತೀರಾ? ({yes} / {no})",
        "slot_error": "ಆ ಭೇಟಿಯ ಸಮಯ ಇನ್ನು ಹೆಚ್ಚು ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೊಂದು ಸಮಯವನ್ನು ಆಯ್ಕೆ ಮಾಡಿರಿ.",
        "selection_error": "ಆ ಆಯ್ಕೆ ನನಗೆ ಅರ್ಥವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಪ್ರದರ್ಶಿತ ಆಯ್ಕೆಗಳಲ್ಲಿ ಒಂದನ್ನು ಆಯ್ಕೆ ಮಾಡಿ."
    },
    "mr": {
        "department_booking_prompt": "{department} डॉक्टरांसोबत अपॉइंटमेंट बुक करू इच्छिता? ({yes} / {no})",
        "booking_prompt": "मी तुम्हाला उपलब्ध अपॉइंटमेंट स्लॉट शोधू? ({yes} / {no})",
        "report_forward_prompt": "तुमची सविस्तर क्लिनिकल रिपोर्ट {doctor} यांना अपॉइंटमेंटपूर्वी फॉरवर्ड करू का? यात आम्ही चर्चा केलेली लक्षणे, पॅटर्न, ट्रिगर्स आणि सूचना समाविष्ट असतील. ({yes} / {no})",
        "appointment_confirmed": "{doctor} यांच्यासोबत तुमची अपॉइंटमेंट {date_time} ला सुनिश्चित करण्यात आली आहे. संदर्भ ID: {reference}.",
        "report_sent": "तुमची क्लिनिकल रिपोर्ट {doctor} यांना पाठवण्यात आलेली आहे.",
        "cancellation_prompt": "{doctor} यांच्यासोबत {date_time} ला तुमची अपॉइंटमेंट रद्द करू इच्छिता? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} यांच्यासोबत {date_time} ला तुमची अपॉइंटमेंट रद्द करण्यात आली आहे.",
        "reschedule_prompt": "{doctor} यांच्यासोबत तुमची अपॉइंटमेंट पुनर्निर्धारित करू इच्छिता? ({yes} / {no})",
        "slot_error": "हा अपॉइंटमेंट स्लॉट आता उपलब्ध नाही. कृपया अन्य स्लॉट निवडा.",
        "selection_error": "मला तो पर्याय समजला नाही. कृपया दर्शवलेल्या पर्यायांपैकी एक निवडा."
    },
    "bn": {
        "department_booking_prompt": "আপনি কি {department} ডাক্তার এর সঙ্গে অ্যাপয়েন্টমেন্ট বুক করতে চান? ({yes} / {no})",
        "booking_prompt": "আমি কি আপনার জন্য উপলব্ধ অ্যাপয়েন্টমেন্ট স্লট খুঁজে দেব? ({yes} / {no})",
        "report_forward_prompt": "আপনার সাক্ষাৎকারের আগে আপনার বিস্তারিত চিকিৎসা প্রতিবেদন {doctor} কে পাঠাতে হবে কি? এতে আমাদের আলোচনা করা লক্ষণগুলি, প্যাটার্ন, ট্রিগার এবং প্রস্তাবনা অন্তর্ভুক্ত থাকবে। ({yes} / {no})",
        "appointment_confirmed": "{doctor} এর সঙ্গে আপনার অ্যাপয়েন্টমেন্ট {date_time} এ নিশ্চিত করা হয়েছে। রেফারেন্স ID: {reference}.",
        "report_sent": "আপনার চিকিৎসা প্রতিবেদন {doctor} কে পাঠানো হয়েছে।",
        "cancellation_prompt": "আপনি কি {date_time} এ {doctor} এর সঙ্গে আপনার অ্যাপয়েন্টমেন্ট বাতিল করতে চান? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} এর সঙ্গে আপনার অ্যাপয়েন্টমেন্ট {date_time} এ বাতিল করা হয়েছে।",
        "reschedule_prompt": "আপনি কি {doctor} এর সঙ্গে আপনার অ্যাপয়েন্টমেন্ট পুনরায় নির্ধারণ করতে চান? ({yes} / {no})",
        "slot_error": "এই অ্যাপয়েন্টমেন্ট স্লট এখন আর উপলব্ধ নেই। অনুগ্রহ করে অন্য স্লট নির্বাচন করুন।",
        "selection_error": "আমি সেই নির্বাচনটি বুঝতে পারিনি। অনুগ্রহ করে প্রদর্শিত বিকল্পগুলির একটি বেছে নিন।"
    },
    "gu": {
        "department_booking_prompt": "શું તમે {department} ડોક્ટર સાથે નિમણુંક બુક કરવા માંગો છો? ({yes} / {no})",
        "booking_prompt": "શું હું તમારી માટે ઉપલબ્ધ નિમણુંક સ્લોટ્સ શોધી આપું? ({yes} / {no})",
        "report_forward_prompt": "શુ હું તમારી વિગતવાર ક્લિનિકલ રિપોર્ટ {doctor} ને તમારી નિમણુંક અગાઉ મોકલુ? જેમાં અમે ચર્ચા કરેલા લક્ષણો, પેટર્ન, ટ્રિગર્સ અને ભલામણો શામેલ હશે. ({yes} / {no})",
        "appointment_confirmed": "{doctor} સાથે તમારા નિમણુંક {date_time} માટે આધીન છે. રેફરન્સ ID: {reference}.",
        "report_sent": "તમારી ક્લિનિકલ રિપોર્ટ {doctor} ને મોકલવામાં આવી છે.",
        "cancellation_prompt": "{doctor} સાથે {date_time}ને તમારી નિમણુંક રદ કરવા માંગો છો? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} સાથે તમારી નિમણુંક {date_time} રદ કરવામાં આવી છે.",
        "reschedule_prompt": "{doctor} સાથેથી તમારી નિમણુંક ફરીથી શેડ્યૂલ કરવા માંગો છો? ({yes} / {no})",
        "slot_error": "તે નિમણુંક સ્લોટ હવે ઉપલબ્ધ નથી. કૃપા કરીને બીજો સ્લોટ પસંદ કરો.",
        "selection_error": "મને તે પસંદગી સમજી ના શકયો. કૃપા કરી દર્શાવેલા વિકલ્પોમાંથી કોઈ એક પસંદ કરો."
    }
}
FULL_WORKFLOW_MESSAGES.update({
    "es": {
        "department_booking_prompt": "¿Le gustaría reservar una cita con un médico de {department}? ({yes} / {no})",
        "booking_prompt": "¿Quiere que busque horarios de citas disponibles para usted? ({yes} / {no})",
        "report_forward_prompt": "¿Debería enviar su informe clínico detallado a {doctor} antes de su cita? Esto incluirá los síntomas, patrones, desencadenantes y recomendaciones que discutimos. ({yes} / {no})",
        "appointment_confirmed": "Su cita con {doctor} está confirmada para el {date_time}. ID de referencia: {reference}.",
        "report_sent": "Su informe clínico ha sido enviado a {doctor}.",
        "cancellation_prompt": "¿Desea cancelar su cita con {doctor} el {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Su cita con {doctor} el {date_time} ha sido cancelada.",
        "reschedule_prompt": "¿Desea reprogramar su cita con {doctor}? ({yes} / {no})",
        "slot_error": "Ese horario de cita ya no está disponible. Por favor elija otro horario.",
        "selection_error": "No pude entender esa selección. Por favor elija una de las opciones mostradas."
    },
    "fr": {
        "department_booking_prompt": "Souhaitez-vous prendre rendez-vous avec un médecin de {department} ? ({yes} / {no})",
        "booking_prompt": "Voulez-vous que je trouve des plages de rendez-vous disponibles pour vous ? ({yes} / {no})",
        "report_forward_prompt": "Dois-je envoyer votre rapport clinique détaillé à {doctor} avant votre rendez-vous ? Cela inclura les symptômes, modèles, déclencheurs et recommandations que nous avons discutés. ({yes} / {no})",
        "appointment_confirmed": "Votre rendez-vous avec {doctor} est confirmé pour le {date_time}. ID de référence : {reference}.",
        "report_sent": "Votre rapport clinique a été envoyé à {doctor}.",
        "cancellation_prompt": "Souhaitez-vous annuler votre rendez-vous avec {doctor} le {date_time} ? ({yes} / {no})",
        "cancellation_confirmed": "Votre rendez-vous avec {doctor} le {date_time} a été annulé.",
        "reschedule_prompt": "Souhaitez-vous reprogrammer votre rendez-vous avec {doctor} ? ({yes} / {no})",
        "slot_error": "Ce créneau de rendez-vous n'est plus disponible. Veuillez choisir un autre créneau.",
        "selection_error": "Je n'ai pas pu comprendre cette sélection. Veuillez choisir l'une des options affichées."
    },
    "de": {
        "department_booking_prompt": "Möchten Sie einen Termin bei einem {department}-Arzt buchen? ({yes} / {no})",
        "booking_prompt": "Möchten Sie, dass ich verfügbare Termine für Sie finde? ({yes} / {no})",
        "report_forward_prompt": "Soll ich Ihren detaillierten klinischen Bericht vor Ihrem Termin an {doctor} weiterleiten? Dies wird die Symptome, Muster, Auslöser und Empfehlungen, die wir besprochen haben, enthalten. ({yes} / {no})",
        "appointment_confirmed": "Ihr Termin mit {doctor} ist für den {date_time} bestätigt. Referenz-ID: {reference}.",
        "report_sent": "Ihr klinischer Bericht wurde an {doctor} gesendet.",
        "cancellation_prompt": "Möchten Sie Ihren Termin mit {doctor} am {date_time} stornieren? ({yes} / {no})",
        "cancellation_confirmed": "Ihr Termin mit {doctor} am {date_time} wurde storniert.",
        "reschedule_prompt": "Möchten Sie Ihren Termin mit {doctor} verschieben? ({yes} / {no})",
        "slot_error": "Dieser Termin ist nicht mehr verfügbar. Bitte wählen Sie einen anderen Termin.",
        "selection_error": "Ich konnte diese Auswahl nicht verstehen. Bitte wählen Sie eine der angezeigten Optionen aus."
    },
    "it": {
        "department_booking_prompt": "Vuole prenotare un appuntamento con un medico di {department}? ({yes} / {no})",
        "booking_prompt": "Vuole che cerchi per lei le fasce orarie disponibili? ({yes} / {no})",
        "report_forward_prompt": "Devo inviare il suo rapporto clinico dettagliato a {doctor} prima del suo appuntamento? Questo includerà i sintomi, i modelli, i fattori scatenanti e le raccomandazioni di cui abbiamo discusso. ({yes} / {no})",
        "appointment_confirmed": "Il suo appuntamento con {doctor} è confermato per {date_time}. ID di riferimento: {reference}.",
        "report_sent": "Il suo rapporto clinico è stato inviato a {doctor}.",
        "cancellation_prompt": "Vuole annullare il suo appuntamento con {doctor} il {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Il suo appuntamento con {doctor} il {date_time} è stato annullato.",
        "reschedule_prompt": "Vuole riprogrammare il suo appuntamento con {doctor}? ({yes} / {no})",
        "slot_error": "Quello slot di appuntamento non è più disponibile. Si prega di scegliere un altro slot.",
        "selection_error": "Non sono riuscito a capire quella scelta. Si prega di scegliere una delle opzioni visualizzate."
    },
    "pt": {
        "department_booking_prompt": "Gostaria de marcar uma consulta com um médico de {department}? ({yes} / {no})",
        "booking_prompt": "Gostaria que eu encontrasse horários de consulta disponíveis para você? ({yes} / {no})",
        "report_forward_prompt": "Devo enviar seu relatório clínico detalhado para {doctor} antes de sua consulta? Isso incluirá os sintomas, padrões, gatilhos e recomendações que discutimos. ({yes} / {no})",
        "appointment_confirmed": "Sua consulta com {doctor} está confirmada para {date_time}. ID de referência: {reference}.",
        "report_sent": "Seu relatório clínico foi enviado para {doctor}.",
        "cancellation_prompt": "Gostaria de cancelar sua consulta com {doctor} em {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Sua consulta com {doctor} em {date_time} foi cancelada.",
        "reschedule_prompt": "Gostaria de reagendar sua consulta com {doctor}? ({yes} / {no})",
        "slot_error": "Esse horário de consulta não está mais disponível. Por favor, escolha outro horário.",
        "selection_error": "Não consegui entender essa seleção. Por favor escolha uma das opções exibidas."
    },
    "ru": {
        "department_booking_prompt": "Вы хотите записаться на прием к доктору {department}? ({yes} / {no})",
        "booking_prompt": "Хотите, чтобы я нашел для вас доступные слоты для записи? ({yes} / {no})",
        "report_forward_prompt": "Отправить ли ваш подробный клинический отчет {doctor} перед вашим визитом? Это будет включать симптомы, шаблоны, триггеры и рекомендации, которые мы обсуждали. ({yes} / {no})",
        "appointment_confirmed": "Ваш прием с {doctor} подтвержден на {date_time}. Идентификатор справки: {reference}.",
        "report_sent": "Ваш клинический отчет отправлен {doctor}.",
        "cancellation_prompt": "Хотите отменить вашу запись с {doctor} на {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Ваша запись к {doctor} на {date_time} была отменена.",
        "reschedule_prompt": "Хотите перенести ваш прием с {doctor}? ({yes} / {no})",
        "slot_error": "Этот временной интервал для записи больше недоступен. Пожалуйста, выберите другой слот.",
        "selection_error": "Я не смог понять этот выбор. Пожалуйста, выберите один из предложенных вариантов."
    },
    "pl": {
        "department_booking_prompt": "Czy chcesz umówić się na wizytę u lekarza {department}? ({yes} / {no})",
        "booking_prompt": "Czy chcesz, abym znalazł dla ciebie dostępne terminy wizyt? ({yes} / {no})",
        "report_forward_prompt": "Czy wysłać twój szczegółowy raport kliniczny do {doctor} przed twoją wizytą? Zawiera on objawy, schematy, czynniki wywołujące i zalecenia, o których rozmawialiśmy. ({yes} / {no})",
        "appointment_confirmed": "Twoja wizyta u {doctor} jest potwierdzona na {date_time}. ID referencyjny: {reference}.",
        "report_sent": "Twój raport kliniczny został wysłany do {doctor}.",
        "cancellation_prompt": "Czy chcesz anulować swoją wizytę u {doctor} na {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Twoja wizyta u {doctor} na {date_time} została anulowana.",
        "reschedule_prompt": "Czy chcesz przełożyć swoją wizytę u {doctor}? ({yes} / {no})",
        "slot_error": "Ten termin wizyty nie jest już dostępny. Proszę wybrać inny termin.",
        "selection_error": "Nie udało mi się zrozumieć tego wyboru. Proszę wybrać jedną z wyświetlonych opcji."
    },
    "nl": {
        "department_booking_prompt": "Wilt u een afspraak maken met een {department} arts? ({yes} / {no})",
        "booking_prompt": "Wilt u dat ik beschikbare afspraakopties voor u zoek? ({yes} / {no})",
        "report_forward_prompt": "Moet ik uw gedetailleerde klinische rapport aan {doctor} sturen vóór uw afspraak? Dit zal de symptomen, patronen, triggers en aanbevelingen bevatten die we hebben besproken. ({yes} / {no})",
        "appointment_confirmed": "Uw afspraak met {doctor} is bevestigd voor {date_time}. Referentie-ID: {reference}.",
        "report_sent": "Uw klinische rapport is verzonden naar {doctor}.",
        "cancellation_prompt": "Wilt u uw afspraak met {doctor} op {date_time} annuleren? ({yes} / {no})",
        "cancellation_confirmed": "Uw afspraak met {doctor} op {date_time} is geannuleerd.",
        "reschedule_prompt": "Wilt u uw afspraak met {doctor} verplaatsen? ({yes} / {no})",
        "slot_error": "Dat tijdslot is niet langer beschikbaar. Kies alstublieft een andere tijd.",
        "selection_error": "Ik kon die selectie niet begrijpen. Kies alstublieft een van de weergegeven opties."
    }
})
FULL_WORKFLOW_MESSAGES.update({
    "tr": {
        "department_booking_prompt": "{department} doktoru ile randevu almak ister misiniz? ({yes} / {no})",
        "booking_prompt": "Sizin için uygun randevu saatleri bulmamı ister misiniz? ({yes} / {no})",
        "report_forward_prompt": "Detaylı klinik raporunuzu randevunuzdan önce {doctor} doktoruna ileteyim mi? Bu rapor, tartıştığımız semptomları, paternleri, tetikleyicileri ve önerileri içerecektir. ({yes} / {no})",
        "appointment_confirmed": "{doctor} ile olan randevunuz {date_time} tarihinde onaylanmıştır. Referans ID: {reference}.",
        "report_sent": "Klinik raporunuz {doctor} doktoruna gönderildi.",
        "cancellation_prompt": "{date_time} tarihinde {doctor} doktoru ile olan randevunuzu iptal etmek ister misiniz? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} doktoru ile {date_time} tarihinde olan randevunuz iptal edilmiştir.",
        "reschedule_prompt": "{doctor} doktoru ile olan randevunuzu tekrar planlamak ister misiniz? ({yes} / {no})",
        "slot_error": "Bu randevu saati artık mevcut değil. Lütfen başka bir saat seçin.",
        "selection_error": "Bu seçimi anlayamadım. Lütfen görüntülenen seçeneklerden birini seçin."
    },
    "ar": {
        "department_booking_prompt": "هل ترغب في حجز موعد مع طبيب {department}؟ ({yes} / {no})",
        "booking_prompt": "هل تريد مني العثور على مواعيد متاحة لك؟ ({yes} / {no})",
        "report_forward_prompt": "هل ينبغي أن أرسل تقريرك السريري المفصل إلى {doctor} قبل موعدك؟ سيتضمن هذا الأعراض والأنماط والمحفزات والتوصيات التي ناقشناها. ({yes} / {no})",
        "appointment_confirmed": "تم تأكيد موعدك مع {doctor} في {date_time}. رقم المرجع: {reference}.",
        "report_sent": "تم إرسال تقريرك السريري إلى {doctor}.",
        "cancellation_prompt": "هل ترغب في إلغاء موعدك مع {doctor} في {date_time}؟ ({yes} / {no})",
        "cancellation_confirmed": "تم إلغاء موعدك مع {doctor} في {date_time}.",
        "reschedule_prompt": "هل ترغب في إعادة جدولة موعدك مع {doctor}؟ ({yes} / {no})",
        "slot_error": "هذا الموعد لم يعد متاحًا. الرجاء اختيار موعد آخر.",
        "selection_error": "لم أتمكن من فهم هذا الاختيار. من فضلك اختر أحد الخيارات المعروضة."
    },
    "he": {
        "department_booking_prompt": "האם ברצונך לקבוע תור עם רופא {department}? ({yes} / {no})",
        "booking_prompt": "האם תרצה שאמצא עבורך מועדי תור זמינים? ({yes} / {no})",
        "report_forward_prompt": "האם להעביר את הדוח הקליני המפורט שלך ל-{doctor} לפני התור שלך? זה יכלול את התסמינים, דפוסים, גורמים ממטירי והמלצות שדיברנו עליהם. ({yes} / {no})",
        "appointment_confirmed": "התור שלך עם {doctor} אושר ל-{date_time}. מזהה הפניה: {reference}.",
        "report_sent": "הדו\"ח הקליני שלך נשלח ל-{doctor}.",
        "cancellation_prompt": "האם תרצה לבטל את התור שלך עם {doctor} ב-{date_time}? ({yes} / {no})",
        "cancellation_confirmed": "התור שלך עם {doctor} ב-{date_time} בוטל.",
        "reschedule_prompt": "האם תרצה לתזמן מחדש את התור שלך עם {doctor}? ({yes} / {no})",
        "slot_error": "מועד התור הזה אינו זמין יותר. אנא בחר מועד אחר.",
        "selection_error": "לא הבנתי את הבחירה הזו. אנא בחר אחת מהאפשרויות המוצגות."
    },
    "fa": {
        "department_booking_prompt": "آیا مایلید وقت ملاقات با دکتر {department} را تعیین کنید؟ ({yes} / {no})",
        "booking_prompt": "آیا می‌خواهید وقت‌های ملاقات موجود را برایتان پیدا کنم؟ ({yes} / {no})",
        "report_forward_prompt": "آیا گزارش جامع بالینی شما پیش از ملاقات به {doctor} ارسال شود؟ این شامل علائم، الگوها، محرک‌ها و توصیه‌هایی‌ است که بحث کردیم. ({yes} / {no})",
        "appointment_confirmed": "ملاقات شما با {doctor} برای {date_time} تأیید شد. شماره مرجع: {reference}.",
        "report_sent": "گزارش بالینی شما به {doctor} ارسال شد.",
        "cancellation_prompt": "آیا می‌خواهید ملاقات خود با {doctor} در {date_time} را لغو کنید؟ ({yes} / {no})",
        "cancellation_confirmed": "ملاقات شما با {doctor} در {date_time} لغو شد.",
        "reschedule_prompt": "آیا می‌خواهید ملاقات خود با {doctor} را دوباره تنظیم کنید؟ ({yes} / {no})",
        "slot_error": "این زمان ملاقات دیگر در دسترس نیست. لطفاً زمان دیگری را انتخاب کنید.",
        "selection_error": "نمی‌توانم این انتخاب را بفهمم. لطفاً یکی از گزینه‌های نمایش داده شده را انتخاب کنید."
    },
    "sw": {
        "department_booking_prompt": "Ungependa kuweka miadi na daktari wa {department}? ({yes} / {no})",
        "booking_prompt": "Ungependa nitafute vipindi vya miadi vilivyopo kwa ajili yako? ({yes} / {no})",
        "report_forward_prompt": "Je, nipeleke ripoti yako ya kliniki ya kina kwa {doctor} kabla ya miadi yako? Hii itajumuisha dalili, mifumo, vichochezi, na mapendekezo tuliyojadili. ({yes} / {no})",
        "appointment_confirmed": "Miadi yako na {doctor} imethibitishwa kwa {date_time}. Kitambulisho cha Rejea: {reference}.",
        "report_sent": "Ripoti yako ya kliniki imepelekwa kwa {doctor}.",
        "cancellation_prompt": "Ungependa kufuta miadi yako na {doctor} mnamo {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Miadi yako na {doctor} mnamo {date_time} imefutwa.",
        "reschedule_prompt": "Ungependa kupanga upya miadi yako na {doctor}? ({yes} / {no})",
        "slot_error": "Kipindi hicho cha miadi hakipatikani tena. Tafadhali chagua kipindi kingine.",
        "selection_error": "Sikuweza kuelewa chaguo hilo. Tafadhali chagua mojawapo ya chaguo zilizowekwa."
    },
    "el": {
        "department_booking_prompt": "Θα θέλατε να κλείσετε ραντεβού με γιατρό {department}; ({yes} / {no})",
        "booking_prompt": "Θα θέλατε να βρω διαθέσιμα slots ραντεβού για εσάς; ({yes} / {no})",
        "report_forward_prompt": "Να προωθήσω την αναλυτική κλινική σας αναφορά στη {doctor} πριν το ραντεβού σας; Αυτό θα περιλαμβάνει τα συμπτώματα, τα πρότυπα, τις παραμέτρους και τις συστάσεις που συζητήσαμε. ({yes} / {no})",
        "appointment_confirmed": "Το ραντεβού σας με {doctor} επιβεβαιώθηκε για τις {date_time}. Κωδικός Αναφοράς: {reference}.",
        "report_sent": "Η κλινική σας αναφορά εστάλη στο {doctor}.",
        "cancellation_prompt": "Θα θέλατε να ακυρώσετε το ραντεβού σας με τον {doctor} στις {date_time}; ({yes} / {no})",
        "cancellation_confirmed": "Το ραντεβού σας με τον {doctor} στις {date_time} ακυρώθηκε.",
        "reschedule_prompt": "Θα θέλατε να προγραμματίσετε εκ νέου το ραντεβού σας με τον {doctor}; ({yes} / {no})",
        "slot_error": "Αυτό το ραντεβού δεν είναι πλέον διαθέσιμο. Παρακαλώ επιλέξτε άλλο χρονικό διάστημα.",
        "selection_error": "Δεν κατάφερα να κατανοήσω αυτή την επιλογή. Παρακαλώ επιλέξτε μία από τις εμφανιζόμενες επιλογές."
    },
    "zh": {
        "department_booking_prompt": "您想预约 {department} 医生的看诊吗？（{yes} / {no}）",
        "booking_prompt": "您想让我为您查找可用的预约时间吗？（{yes} / {no}）",
        "report_forward_prompt": "我可以在您预约前将您的详细临床报告转发给 {doctor} 吗？这将包括我们讨论的症状、模式、诱因和建议。（{yes} / {no}）",
        "appointment_confirmed": "您与 {doctor} 的预约在 {date_time} 已确认。参考编号：{reference}。",
        "report_sent": "您的临床报告已发送给 {doctor}。",
        "cancellation_prompt": "您想取消 {date_time} 与 {doctor} 的预约吗？（{yes} / {no}）",
        "cancellation_confirmed": "您与 {doctor} 在 {date_time} 的预约已取消。",
        "reschedule_prompt": "您想重新安排与 {doctor} 的预约时间吗？（{yes} / {no}）",
        "slot_error": "该预约时间段已不再可用。请选择其他时间段。",
        "selection_error": "我无法理解您的选择。请选择显示的选项之一。"
    },
    "ja": {
        "department_booking_prompt": "{department}医師の診察を予約しますか？（{yes} / {no}）",
        "booking_prompt": "利用可能な予約スロットをお探ししますか？（{yes} / {no}）",
        "report_forward_prompt": "診察前に詳細な臨床報告を{doctor}に転送しますか？これには、私たちが話し合った症状、パターン、トリガー、および推奨事項が含まれます。（{yes} / {no}）",
        "appointment_confirmed": "{doctor}との予約は{date_time}に確認されました。参照ID：{reference}。",
        "report_sent": "あなたの臨床報告は{doctor}に送信されました。",
        "cancellation_prompt": "{date_time}の{doctor}との予約をキャンセルしますか？（{yes} / {no}）",
        "cancellation_confirmed": "{doctor}との{date_time}の予約はキャンセルされました。",
        "reschedule_prompt": "{doctor}との予約を再スケジュールしますか？（{yes} / {no}）",
        "slot_error": "その予約スロットはもう利用できません。別のスロットを選択してください。",
        "selection_error": "その選択が理解できませんでした。表示されているオプションの中から選択してください。"
    }
})
FULL_WORKFLOW_MESSAGES.update({
    "ko": {
        "department_booking_prompt": "{department} 의사와 진료 예약을 하시겠습니까? ({yes} / {no})",
        "booking_prompt": "가능한 예약 시간을 찾아드릴까요? ({yes} / {no})",
        "report_forward_prompt": "예약 전 {doctor}에게 상세한 임상 보고서를 전달할까요? 이를 통해 우리가 논의한 증상, 패턴, 유발 요인 및 권장 사항을 포함합니다. ({yes} / {no})",
        "appointment_confirmed": "{doctor}와의 예약이 {date_time}로 확인되었습니다. 참조 ID: {reference}.",
        "report_sent": "당신의 임상 보고서가 {doctor}에게 전달되었습니다.",
        "cancellation_prompt": "{date_time}에 {doctor}와의 예약을 취소하시겠습니까? ({yes} / {no})",
        "cancellation_confirmed": "{date_time}에 {doctor}와의 예약이 취소되었습니다.",
        "reschedule_prompt": "{doctor}와의 예약을 다시 잡으시겠습니까? ({yes} / {no})",
        "slot_error": "그 예약 시간은 더 이상 사용할 수 없습니다. 다른 시간을 선택해 주세요.",
        "selection_error": "선택을 이해할 수 없습니다. 표시된 옵션 중 하나를 선택해 주세요."
    },
    "th": {
        "department_booking_prompt": "คุณต้องการจองนัดกับหมอแผนก {department} หรือไม่? ({yes} / {no})",
        "booking_prompt": "ให้ฉันช่วยหาช่วงเวลานัดที่ว่างให้คุณไหม? ({yes} / {no})",
        "report_forward_prompt": "ควรส่งรายงานทางคลินิกโดยละเอียดให้ {doctor} ก่อนนัดหมายของคุณหรือไม่? จะรวมถึงอาการ, รูปแบบ, สาเหตุ และคำแนะนำที่เราได้พูดคุยกันไว้ ({yes} / {no})",
        "appointment_confirmed": "นัดหมายของคุณกับ {doctor} ได้รับการยืนยันแล้วใน {date_time} หมายเลขอ้างอิง: {reference}.",
        "report_sent": "รายงานทางคลินิกของคุณได้ถูกส่งไปยัง {doctor}.",
        "cancellation_prompt": "คุณต้องการยกเลิกนัดกับ {doctor} ในวันที่ {date_time} หรือไม่? ({yes} / {no})",
        "cancellation_confirmed": "การนัดหมายกับ {doctor} ในวันที่ {date_time} ได้ถูกยกเลิกแล้ว.",
        "reschedule_prompt": "คุณต้องการเลื่อนนัดหมายกับ {doctor} หรือไม่? ({yes} / {no})",
        "slot_error": "ช่วงเวลานัดนี้ไม่มีแล้ว กรุณาเลือกช่วงเวลาอื่น.",
        "selection_error": "ฉันไม่เข้าใจในสิ่งที่คุณเลือก กรุณาเลือกหนึ่งในตัวเลือกที่แสดง."
    },
    "vi": {
        "department_booking_prompt": "Bạn có muốn đặt hẹn với bác sĩ khoa {department} không? ({yes} / {no})",
        "booking_prompt": "Bạn có muốn tôi tìm thời gian hẹn còn trống cho bạn không? ({yes} / {no})",
        "report_forward_prompt": "Tôi có nên gửi báo cáo lâm sàng chi tiết của bạn cho {doctor} trước khi hẹn không? Điều này sẽ bao gồm các triệu chứng, mẫu, tác nhân kích thích và khuyến nghị mà chúng ta đã thảo luận. ({yes} / {no})",
        "appointment_confirmed": "Cuộc hẹn của bạn với {doctor} đã được xác nhận vào {date_time}. Mã tham chiếu: {reference}.",
        "report_sent": "Báo cáo lâm sàng của bạn đã được gửi tới {doctor}.",
        "cancellation_prompt": "Bạn có muốn hủy cuộc hẹn với {doctor} vào {date_time} không? ({yes} / {no})",
        "cancellation_confirmed": "Cuộc hẹn của bạn với {doctor} vào {date_time} đã bị hủy.",
        "reschedule_prompt": "Bạn có muốn dời lại cuộc hẹn với {doctor} không? ({yes} / {no})",
        "slot_error": "Khoảng thời gian hẹn này không còn nữa. Vui lòng chọn khoảng thời gian khác.",
        "selection_error": "Tôi không thể hiểu lựa chọn của bạn. Vui lòng chọn một trong những tùy chọn hiển thị."
    },
    "id": {
        "department_booking_prompt": "Apakah Anda ingin membuat janji dengan dokter {department}? ({yes} / {no})",
        "booking_prompt": "Apakah Anda ingin saya mencari slot waktu yang tersedia untuk Anda? ({yes} / {no})",
        "report_forward_prompt": "Haruskah saya meneruskan laporan klinis rinci Anda ke {doctor} sebelum janji Anda? Ini akan mencakup gejala, pola, pemicu, dan rekomendasi yang telah kita diskusikan. ({yes} / {no})",
        "appointment_confirmed": "Janji Anda dengan {doctor} dikonfirmasi untuk {date_time}. Nomor referensi: {reference}.",
        "report_sent": "Laporan klinis Anda telah dikirim ke {doctor}.",
        "cancellation_prompt": "Apakah Anda ingin membatalkan janji dengan {doctor} pada {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Janji Anda dengan {doctor} pada {date_time} telah dibatalkan.",
        "reschedule_prompt": "Apakah Anda ingin menjadwal ulang janji dengan {doctor}? ({yes} / {no})",
        "slot_error": "Slot waktu janji tersebut sudah tidak tersedia. Silakan pilih slot lain.",
        "selection_error": "Saya tidak dapat memahami pilihan Anda. Silakan pilih salah satu opsi yang ditampilkan."
    },
    "ms": {
        "department_booking_prompt": "Adakah anda ingin menempah temu janji dengan doktor {department}? ({yes} / {no})",
        "booking_prompt": "Adakah anda ingin saya mencari slot temu janji yang tersedia untuk anda? ({yes} / {no})",
        "report_forward_prompt": "Perlukah saya menghantar laporan klinikal terperinci anda kepada {doctor} sebelum temu janji anda? Ini akan termasuk gejala, corak, pencetus, dan saranan yang kita bincangkan. ({yes} / {no})",
        "appointment_confirmed": "Temu janji anda dengan {doctor} telah disahkan untuk {date_time}. ID rujukan: {reference}.",
        "report_sent": "Laporan klinikal anda telah dihantar kepada {doctor}.",
        "cancellation_prompt": "Adakah anda ingin membatalkan temu janji dengan {doctor} pada {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Temu janji anda dengan {doctor} pada {date_time} telah dibatalkan.",
        "reschedule_prompt": "Adakah anda ingin menjadualkan semula temu janji anda dengan {doctor}? ({yes} / {no})",
        "slot_error": "Slot temu janji itu sudah tiada. Sila pilih slot lain.",
        "selection_error": "Saya tidak dapat memahami pilihan itu. Sila pilih salah satu pilihan yang dipaparkan."
    },
    "tl": {
        "department_booking_prompt": "Nais mo bang magpa-book ng appointment sa isang doktor ng {department}? ({yes} / {no})",
        "booking_prompt": "Nais mo bang hanapan kita ng mga available na oras para sa appointment? ({yes} / {no})",
        "report_forward_prompt": "Dapat ko bang ipadala ang detalyadong ulat klinikal sa {doctor} bago ang iyong appointment? Kabilang dito ang mga sintomas, pattern, trigger, at mga rekomendasyon na tinalakay natin. ({yes} / {no})",
        "appointment_confirmed": "Kumpirmado na ang iyong appointment kay {doctor} sa {date_time}. Reference ID: {reference}.",
        "report_sent": "Ang iyong ulat klinikal ay naipadala na kay {doctor}.",
        "cancellation_prompt": "Nais mo bang kanselahin ang iyong appointment kay {doctor} sa {date_time}? ({yes} / {no})",
        "cancellation_confirmed": "Kinansela na ang iyong appointment kay {doctor} sa {date_time}.",
        "reschedule_prompt": "Nais mo bang i-reschedule ang iyong appointment kay {doctor}? ({yes} / {no})",
        "slot_error": "Hindi na available ang oras na iyon. Paki-pili ng ibang oras.",
        "selection_error": "Hindi ko maunawaan ang iyong napili. Paki-pili ng isa sa mga ipinakitang opsyon."
    },
    "my": {
        "department_booking_prompt": "{department} ဆရာဝန်နှင့် ချိန်းဆိုဆိုုင်ကြစီမည်လား? ({yes} / {no})",
        "booking_prompt": "ချိန်းဆိုအချိန်ကျန်ရစ်တာများ ရှာဖွေမလား? ({yes} / {no})",
        "report_forward_prompt": "သင့်ရဲ့ ရောဂါဖျော်ဖြေရေးအကြောင်းအရာကိုပုံမှန်နေစဉ်အားဖြင့် သက်ဆိုင်ရာဆရာဝန် {doctor} ထံကိုမခင်နေ့ {doctor} ကိုပေးပို့လိုသလား။ အဆောက်အအုံမှာ ပြန်လည်ခဲ့သည့်လစဉ်စဉ်အတွင်းတွင်ဖြစ်နေသည့် အခြေအနေများ၊ မှတ်တမ်းများအတွက် အောက်ဆုံးထပ်ကိုပြန်လည်၀င်ယူခြင်းနှင့် အကြံပြုချက်များကိုဖြစ်စေသည်။ ({yes} / {no})",
        "appointment_confirmed": "{doctor} ဦးဆောင်မှုဖြင့် {date_time} ၌ ချိန်းဆိုမှုသည်အခွင့်အလမ်းကိုအတည်ပြုပြီးပါပြီ။ အကြောင်းပြချက်အမှတ်စဉ်: {reference}.",
        "report_sent": "သင့်ရဲ့ စနစ်တစ်ခုရဲ့ အခြေခံသောรายละเอียดများကို {doctor}에게 ပေးပို့ပြီးပါပြီ။",
        "cancellation_prompt": "{doctor} နဲ့ {date_time} ချိန်းဆိုရေးကိုပယ်ဖျက်မလား? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} နဲ့ {date_time} ချိန်းဆိုမှုကိုပယ်ဖျက်ပြီးပါပြီ။",
        "reschedule_prompt": "သင့်ရဲ့ {doctor} နှင့်ချိန့်ဆိုမှုကိုပြန်လည်ညှိနှိုင်းပါမလား? ({yes} / {no})",
        "slot_error": "ဤချိန်းဆိုမှုအချိန်သည် မရရှိနိုင်ပါ။ ကျေးဇူးပြု၍ နောက်နည်းလမ်းရွေးချယ်ပါ။",
        "selection_error": "သင့်တဲ့ရွေးချယ်မှုကိုလက်ခံမရပါဘူး၊ ပြသထားသောရွေးချယ်စရာများထဲမှတစ်ခုကိုရွေးချယ်ပါ။"
    },
    "km": {
        "department_booking_prompt": "តើអ្នកចង់ទូរទាត់ម៉ោងជួបគ្រូពេទ្យផ្នែក {department} តាមអាវុធករណីមនុស្សដែកម្តុំសារធាតុថ្មីម្តងទៀតទេ? ({yes} / {no})",
        "booking_prompt": "តើអ្នកចង់ឱ្យខ្ញុំស្វែងរកម៉ោងទំនេរដើម្បីធ្វើការណាត់ទេ? ({yes} / {no})",
        "report_forward_prompt": "តើខ្ញុំគួរបញ្ជូនរបាយការណ៍ពិស្តាររបស់អ្នកទៅ {doctor} មុនការណាត់ទេ? នេះនឹងព្រមទាំងរោគសញ្ញា លំនាំ ឧបករណ៍បញ្ចូលខ្វាច និងសមាហរណកម្មដែលយើងបាននិយាយ។ ({yes} / {no})",
        "appointment_confirmed": "ការណាត់ជួបរបស់អ្នកជាមួយ {doctor} ត្រូវបានអនុវត្តនៅ {date_time}។ លេខសំគាល់: {reference}.",
        "report_sent": "របាយការណ៍កាណ៍្រ័ាលចារអ្នកបានបញ្ជូនទៅ {doctor} ហើយ។",
        "cancellation_prompt": "តើអ្នកចង់មោឃទោសការណាត់ជួបជាមួយ {doctor} នៅ {date_time} ទេ? ({yes} / {no})",
        "cancellation_confirmed": "ការណាត់ជួបរបស់អ្នកជាមួយ {doctor} នៅ {date_time} ត្រូវបានលុបចោលហើយ។",
        "reschedule_prompt": "តើអ្នកចង់រៀបរាប់ការណាត់ជួបរបស់អ្នកជាមួយ {doctor} ម្តងទៀតទេ? ({yes} / {no})",
        "slot_error": "រយៈពេលនៃការណាត់ភ្លោះមិនបានទទួលធ្វើការចូលដំណើរ. សូមជ្រើសរើសរយៈពេលផ្សេងទៀត។",
        "selection_error": "ខ្ញុំមិនអាចយល់កម្រាចមិនបានជ្រើសរូបភាពុសារព័ត៌មានរបស់អ្នក។ សូមជ្រើសរើសមួយក្នុងចំណោមជម្រើសដែលបានបង្ហាញ។"
    }
})
FULL_WORKFLOW_MESSAGES.update({
    "si": {
        "department_booking_prompt": "{department} වෛද්‍යවරයෙකුගෙන් අවමංගල්‍යයක් වෙන්දේයකිද? ({yes} / {no})",
        "booking_prompt": "ඔබට හොඳ අවමංගල්‍ය වේලාවක් ගණන් බැලීමට කැමතිද? ({yes} / {no})",
        "report_forward_prompt": "ඔබේ විශේෂිත වෛද්‍ය වාර්තාව {doctor} වෙත යැවිය යුතු බවට ඔබට අවශ්‍යද? මෙම වාර්තාවේ සලකුණු, රටාවන්, ජීවකරයන් හා නිර්දේශ ඇතුළත් වේ. ({yes} / {no})",
        "appointment_confirmed": "ඔබේ {doctor} සමඟ ඊළඟ අවමංගල්‍යය {date_time} သန်. `{reference}` යනු සංකේත අංකයයි.",
        "report_sent": "ඔබේ වෛද්‍ය වාර්තාව {doctor} වෙත යවා ඇත.",
        "cancellation_prompt": "ඔබේ {doctor} සමඟ {date_time} දිනට වෙන් නිසායව අවමංගල්‍යය ඉවත් කරනවාද? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} සමඟ ඔබේ {date_time} අවමංගල්‍යය ඉවත් කර ඇත.",
        "reschedule_prompt": "{doctor} සමඟ ඔබේ අවමංගල්‍යය නැවත ඉල්ලීමට අවශ්‍යද? ({yes} / {no})",
        "slot_error": "එය වෙන් දැදීමේ වේලාව සඳහා නොමැත. කරුණාකර වෙනත් වේලාවක් තෝරන්න.",
        "selection_error": "මා ඔබේ තේරීම තේරුම්ගත නොහැකි විය. කරුණාකර කෙරෙන තේරීම් පිළිබඳ වූ එකක් තෝරන්න."
    },
    "pa": {
        "department_booking_prompt": "ਕੀ ਤੁਸੀਂ {department} ਡਾਕਟਰ ਨਾਲ ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰਨਾ ਚਾਹੋਗੇ? ({yes} / {no})",
        "booking_prompt": "ਕੀ ਤੁਸੀਂ ਮੈਂ ਤੁਸੀਂ ਲਈ ਉਪਲਬਧ ਮੁਲਾਕਾਤ ਦੇ ਸਮੇਂ ਲੱਭਾਂ? ({yes} / {no})",
        "report_forward_prompt": "ਕੀ ਮੈਂ ਤੁਹਾਡੀ ਵਿਸਥਾਰਕ ਚਿਕਿਤਸਕ ਰਿਪੋਰਟ {doctor} ਨੂੰ ਮੁਲਾਕਾਤ ਤੋਂ ਪਹਿਲਾਂ ਭੇਜਾਂ? ਇਸ ਵਿੱਚ ਅਸੀਂ ਚਰਚਾ ਕੀਤੀ ਲੱਛਣ, ਨਮੂਨੇ, ਟ੍ਰਿਗਰ ਅਤੇ ਸਿਫਾਰਿਸ਼ਾਂ ਸ਼ਾਮਲ ਹਨ। ({yes} / {no})",
        "appointment_confirmed": "ਤੁਹਾਡਾ {doctor} ਨਾਲ ਮੁਲਾਕਾਤ {date_time} ਲਈ ਪ੍ਰਸ਼ਾਸਿਤ ਹੋ ਗਿਆ ਹੈ। ਹਵਾਲਾ ਆਈਡੀ: {reference}.",
        "report_sent": "ਤੁਹਾਡੀ ਚਿਕਿਤਸਕ ਰਿਪੋਰਟ {doctor} ਨੂੰ ਭਜੀ ਗਈ ਹੈ।",
        "cancellation_prompt": "ਕੀ ਤੁਸੀਂ {doctor} ਨਾਲ ਆਪਣੀ {date_time} ਦੀ ਮੁਲਾਕਾਤ ਰੱਦ ਕਰਨੀ ਹੈ? ({yes} / {no})",
        "cancellation_confirmed": "ਤੁਹਾਡੀ {doctor} ਨਾਲ {date_time} ਦੀ ਮੁਲਾਕਾਤ ਰੱਦ ਹੋ ਗਈ ਹੈ।",
        "reschedule_prompt": "ਕੀ ਤੁਸੀਂ {doctor} ਨਾਲ ਆਪਣੀ ਮੁਲਾਕਾਤ ਨੂੰ ਦੁਬਾਰਾ ਸਮਾਂ ਦੇਣਾ ਚਾਹੁੰਦੇ ਹੋ? ({yes} / {no})",
        "slot_error": "ਉਹ ਮੁਲਾਕਾਤ ਦੀ ਸਮਾਂ ਸਲਾਟ ਹੁਣ ਉਪਲਬਧ ਨਹੀਂ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਸਮਾਂ ਚੁਣੋ।",
        "selection_error": "ਮੈਂ ਉਸ ਚੋਣ ਨੂੰ ਸਮਝਿਆ ਨਹੀਂ। ਕਿਰਪਾ ਕਰਕੇ ਪ੍ਰਦਰਸ਼ਿਤ ਵਿਕਲਪਾਂ ਵਿੱਚੋਂ ਇੱਕ ਚੁਣੋ।"
    },
    "ml": {
        "department_booking_prompt": "നിങ്ങള്‍ക്ക് {department} ഡോക്ടറുമായി ഒരു അപ്യിന്റ്മെന്റ് ബുക്ക് ചെയ്യണോ? ({yes} / {no})",
        "booking_prompt": "നിങ്ങള്‍ക്കായി ലഭ്യമായ അപ്യിന്റ്മെന്റ് സമയങ്ങള്‍ കണ്ടെത്താന്‍ ഞാന്‍ ശ്രമിക്കണോ? ({yes} / {no})",
        "report_forward_prompt": "നിങ്ങളുടെ വിശദമായ ചികിത്സാ റിപ്പോര്‍ട്ട് ‌‌‌{doctor} യ്ക്ക് അയയ്ക്കണോ? ഇത് നമ്മൾ ചർച്ച ചെയ്ത ലക്ഷണങ്ങൾ, മാതൃകകൾ, ട്രിഗർസും ശുപാർശകളും അടങ്ങിയിരിക്കും. ({yes} / {no})",
        "appointment_confirmed": "നിങ്ങളുടെ {doctor} വേട് {date_time} ന് അപ്യിന്റ്മെന്റ് കൺഫിര്‍മായിരിക്കുന്നു. റഫറന്‍സ് ഐഡി: {reference}.",
        "report_sent": "നിങ്ങളുടെ ചികിത്സാ റിപ്പോർട്ട് {doctor} യ്ക്ക് അയച്ചിരിക്കുന്നു.",
        "cancellation_prompt": "നിങ്ങളുടെ {doctor} ‌‌‌‌‌{date_time} ന്റെ അപ്യിന്റ്മെന്റ് ത്യജിക്കണോ? ({yes} / {no})",
        "cancellation_confirmed": "നിങ്ങളുടെ {doctor}യുടെ {date_time} ന്റെ അപ്യിന്റ്മെന്റ് ത്യജിച്ചിരിക്കുന്നു.",
        "reschedule_prompt": "നിങ്ങളുടെ {doctor} വി‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌‌ നിന്നുള്ളക്ക് ഷെഡ്യുൾ ചെയ്യണോ? ({yes} / {no})",
        "slot_error": "അത് വരുന്ന സമയം ലഭ്യമല്ല. മറ്റൊരു സമയം തിരഞ്ഞെടുക്കുക.",
        "selection_error": "സമയം നേടാന്‍ കഴിയുന്നില്ല. കാണുന്നവയില്‍ ഏതെങ്കിലും തിരഞ്ഞെടുക്കുക."
    },
    "or": {
        "department_booking_prompt": "ଆପଣ କିଛି {department} ଡକ୍ଟରଙ୍କ ସହ ନିୟମିତ କରିବାକୁ ଚାହାଁନ୍ତି କି? ({yes} / {no})",
        "booking_prompt": "ଆପଣ କି ମୋତେ ଟିକେବା ଭିତରୁ ଆପଣଙ୍କ ପାଇଁ ଲଭ୍ୟ ଅପଏଣ୍ଟମେଣ୍ଟ ସ୍ଲଟ୍ ଦେଖିବାକୁ କହିବେ କି? ({yes} / {no})",
        "report_forward_prompt": "ଆପଣଙ୍କର ବିବରଣାତ୍ମକ ୟ଼ାଚନା ରିପୋର୍ଟ {doctor} ପୂର୍ବରୁ ସଂଯୋଗ କରିବାକୁ ଆବଶ୍ୟକ କି? ଏହାରେ ଆମେ ସମ୍ବାଦ କରା ସମ୍ବନ୍ଧ ଲକ୍ଷଣ, ମାଡଡ୍ୟୟନରେ, ଟ୍ରିଗରନ୍ସ ଓ ପରିକଳ୍ପନା ସମାନ୍ତରଳ ହେଉଛି। ({yes} / {no})",
        "appointment_confirmed": "ଆପଣଙ୍କ ଆପଏଣ୍ଟମେଣ୍ଟ {doctor} ସହିତ {date_time} ନିୟମିତ ହୋଇଯାଇଛି.ଗ୍୍ରସ୍କୀପ୍ସ: {reference}.",
        "report_sent": "ଆପଣଙ୍କ ବିଗ୍ସିଶାଇ ୟ଼ାଚନା ରିପୋର୍ଟ {doctor} ନିକଟକୁ ପଠାଇବାକୁ.",
        "cancellation_prompt": "ଆପଣଙ୍କ {doctor} ସେବା {date_time}ରେ ଏହି ଆପଏଣ୍ଟମେଣ୍ଟ କଳ୍ଳର କରିବାକୁ ଚାହାଁନ୍ତି କି? ({yes} / {no})",
        "cancellation_confirmed": "ଆପଣଙ୍କ ଆପଏଣ୍ଟମେଣ୍ଟ {doctor} ସହିତ {date_time} ରେ ବରଖାବନ୍ଧ ହୋଇଯାଇଛି.",
        "reschedule_prompt": "ଆପଣ {doctor} ସହିତ ଆପଣଙ୍କ ଆପଏଣ୍ଟମେଣ୍ଟ ପୁଅଏଣ୍ଟମେଣ୍ଟ ନିୟମନୀତ କରିବାକୁ ଚାହାଁନ୍ତି କି? ({yes} / {no})",
        "slot_error": "ସେ ଆପଏଣ୍ଟମେଣ୍ଟ ସ୍ଲଟ୍ ଏବେ ଲଭ୍ୟ ନାହିଁ. ଅନ୍ୟ କୌଣସି ସ୍ଲଟ୍ ବାଚନନମାନନ୍ତୁ।",
        "selection_error": "ମୁଁ ସେ ପସନ୍ଦଗୁଡ଼ିକୁ ବୁଝି ପାରୁ ନାହିଁ. ଦେଖାଯାଇଥିବା ବିକଳ୍ପଗୁଡ଼ିକୁ ବାଚନମାନନ୍ତୁ।"
    },
    "ur": {
        "department_booking_prompt": "کیا آپ {department} کے ڈاکٹر کے ساتھ ملاقات بُک کرنا چاہیں گے؟ ({yes} / {no})",
        "booking_prompt": "کیا آپ چاہتے ہیں کہ میں آپ کے لئے دستیاب ملاقات کے اوقات تلاش کروں؟ ({yes} / {no})",
        "report_forward_prompt": "کیا آپ چاہتے ہیں کہ آپ کی تفصیلی طبی رپورٹ ملاقات سے پہلے {doctor} کو بھیج دی جائے؟ اس میں وہ علامات، پیٹرنز، ٹرگرز اور سفارشات شامل ہوں گی جن پر ہماری بات چیت ہوئی۔ ({yes} / {no})",
        "appointment_confirmed": "آپ کی ملاقات {doctor} کے ساتھ {date_time} کو کنفرم کردی گئی ہے۔ حوالہ نمبر: {reference}.",
        "report_sent": "آپ کی طبی رپورٹ {doctor} کو بھیج دی گئی ہے۔",
        "cancellation_prompt": "کیا آپ {doctor} کے ساتھ اپنی {date_time} کی ملاقات کا منسوخ کرنا چاہیں گے؟ ({yes} / {no})",
        "cancellation_confirmed": "آپ کی {doctor} کے ساتھ {date_time} کی ملاقات منسوخ کردی گئی ہے۔",
        "reschedule_prompt": "کیا آپ چاہتے ہیں کہ میں {doctor} کے ساتھ آپ کی ملاقات کو دوبارہ شیڈول کروں؟ ({yes} / {no})",
        "slot_error": "یہ ملاقات والا وقت دستیاب نہیں ہے۔ مزید کسی وقت کو منتخب کریں۔",
        "selection_error": "میں آپ کی انتخاب کو سمجھ نہیں سکا۔ براہ کرم دکھائے گئے اختیارات میں سے کسی ایک کو منتخب کریں۔"
    },
    "as": {
        "department_booking_prompt": "আপুনি কি {department} চিকিৎসকৰ সৈতে  দেখা কৰিবলৈ সময় বুকিং কৰিবা পাৰনে? ({yes} / {no})",
        "booking_prompt": "মই কি আপুনি উপলব্ধ সময়ৰ পৰা কোনো কথা বুকিং কৰিম নে? ({yes} / {no})",
        "report_forward_prompt": "আপুনি কি আপুনি বিশেষ ঔষধী ৰিপোৰ্ট জমা দি {doctor}লৈ পাঠাব লাগে? ({yes} / {no})",
        "appointment_confirmed": "আপোনাৰ {doctor} লগত আঁকাম কৰি ছাঁহ বজায়ৰ {date_time} নিশ্চিত কৰা হ'ল। অনুসন্ধান আইডি কাৰ্ড: {reference}.",
        "report_sent": "আপোনাৰ চিকিৎসা ৰিপোৰ্টৰ {doctor}ক প্ৰেৰণ কৰিল।",
        "cancellation_prompt": "আপুনি কি {doctor} ৰ সৈতে {date_time} তাৰিখে আপনাৰ সময় বাতিল কৰাৰ চেষ্টা কৰিম নে? ({yes} / {no})",
        "cancellation_confirmed": "আপোনাৰ {doctor} লগত {date_time} সময় বাতিল কৰা হৈছে।",
        "reschedule_prompt": "আপুনি কি {doctor} লগত {department} সময় বুজা অনুমতি যোগ্য হব কনে? পরিগত লৈ যাওঁ বা নহয়।({yes} / {no})",
        "slot_error": "যি সময় ধেৰ ৰিজাই কৰা হ'ল, তা দুভাত নোহৰহক। দয়া কৰি আনব্য পাৰ্টৰপ জনাবা।",
        "selection_error": "আপনি বিচাৰ অভিযোগ সঠিকৰেক গুৰিয়ে చేయা যায়। পরিগুজন বিদ্যমান ({yes} / {no})"
    },
    "mai": {
        "department_booking_prompt": "अहाँ चाहै छी कि अहाँ {department} डॉक्टर सं भेट कर' लेल नियोजन करबा चाहै छी? ({yes} / {no})",
        "booking_prompt": "अहाँ चाहै छी कि हम अहाँ लेल उपलब्ध नियोजन स्लॉट खोजि दी? ({yes} / {no})",
        "report_forward_prompt": "अहाँ चाहै छी जे अहाँक विस्मयकारी चिकित्सा रिपोर्ट {doctor} सं मिलबाक पहिने ओकरा काळिहऽ दी? एहिमे हम जनि आ चर्चा कयने लक्ष्ण, नमूना, ट्रिगर आ सिफारिश समन्वेषित होयत। ({yes} / {no})",
        "appointment_confirmed": "अहाँक {doctor} सं भेट {date_time} लेल परिषदक भऽ गेल अछि। उद्धृत संदर्भ आईडी: {reference}.",
        "report_sent": "अहाँक चिकित्सा रिपोर्ट {doctor} कऽ कहबाक गेल अछि।",
        "cancellation_prompt": "अहाँ चाहै छथि कि अहाँ {doctor} सं {date_time} कऽ भेटले अहाँक नियुक्ति के रद्द करि देना जाए? ({yes} / {no})",
        "cancellation_confirmed": "अहाँक {doctor} सं {date_time} पर भेट लेल अभियान रद्द कय देल गेल अछि।",
        "reschedule_prompt": "अहाँ चाहै छी कि अहाँक {doctor} सं पुनः संयोजन भेट हेबाक चाही की? ({yes} / {no})",
        "slot_error": "ओ समय नियोजन सुविधा के लेल उपलब्ध नहि अछि। कृपया अन्य समय चयन करू।",
        "selection_error": "मुझे आपकी चयन समझ शुभ, दिखाई गए विकल्पों मीं से एक का चयन करो।"
    },
    "kok": {
        "department_booking_prompt": "तुमका {department} डॉक्टराचेर अपॉइंटमेंट बुक करपाक जाय काय? ({yes} / {no})",
        "booking_prompt": "तुमका उपरलब्ध अपॉइंटमेंट स्लॉट्स वळयाँवाची माका मदत करपाक जाय का? ({yes} / {no})",
        "report_forward_prompt": "तुमचे हवे की तुमचा पांचेवरली आरोवे रक्कम रिपोर्ट {doctor} क बिरुद्ध अमकळें पाठवचेच्या? हे चर्चा रो, चिन्हांकित पॅटर्न, कारणान, आं विकार पैशी परिसंकपणर शामिल करा. ({yes} / {no})",
        "appointment_confirmed": "{doctor} क्व {date_time}-चे अपॉइंटमेंट तुमका शिव्ड केलेला. संदर्भ क्रमांक: {reference}.",
        "report_sent": "तुमचा आरोवे रक्कम रिपोर्ट {doctor} क्व पाठविला किंवा.",
        "cancellation_prompt": "{date_time} चे {doctor} कुण अपॉइंटमेंट फर्क करचे अशी तुमका असलो काय? ({yes} / {no})",
        "cancellation_confirmed": "{date_time} चे {doctor} क्व तुमचा अपॉइंटमेंट फर्क केला गेलो.",
        "reschedule_prompt": "{doctor} चे अपॉइंटमेंट फुड्यार शेड्यूल करपाक जाय काय? ({yes} / {no})",
        "slot_error": "हे अपॉइंटमेंट स्लॉट उपलब्ध ना. त्यांचेर दुसऱ्या वेळा वाडावात.",
        "selection_error": "माका तुमचे चयन स्वतंत्र करताना खराब वटलं. कायलेला विकल्पांतून एक विकल्प चयन कराव."
    }
})
FULL_WORKFLOW_MESSAGES.update({
    "ne": {
        "department_booking_prompt": "तपाइँ {department} चिकित्सकसँग भेटवार्ता निर्धारण गर्न चाहनुहुन्छ? ({yes} / {no})",
        "booking_prompt": "के म तपाईँको लागि उपलब्ध भेटवार्ता समय भेट्टाउन सक्छु? ({yes} / {no})",
        "report_forward_prompt": "के म तपाइँको विस्तृत चिकित्सकीय प्रतिवेदन {doctor} लाई तपाइँको भेटघाट अघि अग्रेषण गर्न सक्छु? यसमा हामीले छलफल गरेका लक्षण, नमूना, ट्रिगरहरू, र सिफारिसहरू समावेश हुनेछ। ({yes} / {no})",
        "appointment_confirmed": "{doctor} सँग तपाइँको भेटघाट {date_time} मा पुष्टि गरियो। सन्दर्भ ID: {reference}.",
        "report_sent": "तपाईँको चिकित्सकीय प्रतिवेदन {doctor} लाई पठाइएको छ।",
        "cancellation_prompt": "के तपाईँ {date_time} मा {doctor} को साथतपाईंको भेटघाट रद्द गर्न चाहनुहुन्छ? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} सँग तपाईँको {date_time} को भेटघाट रद्द भएको छ।",
        "reschedule_prompt": "के तपाईँ {doctor} सँग तपाईँको भेटघाट पुनःतालिका गर्न चाहनुहुन्छ? ({yes} / {no})",
        "slot_error": "त्यो भेटघाट समय अब उपलब्ध छैन। कृपया अर्को समय छनौट गर्नुहोस्।",
        "selection_error": "म त्यो चयन बुझ्न सकिनँ। कृपया देखाइएको विकल्पहरू मध्ये एक छनौट गर्नुहोस्।"
    },
    "sd": {
        "department_booking_prompt": "ڇا توهان {department} جي ڊاڪٽر سان ملاقات جو وقت وٺڻ چاهيو ٿا؟ ({yes} / {no})",
        "booking_prompt": "ڇا آئون توهان لاءِ دستياب ملاقاتن جا وقت وٺي سگهان ٿو؟ ({yes} / {no})",
        "report_forward_prompt": "ڇا مون کي توهان جي تفصيلي ڪلينڪل رپورٽ {doctor} کي ملاقات کان اڳ موڪلي ڇڏيان؟ هن ۾ اسان جا بحث ٿيل علامات، نمونا، محرڪات، ۽ سفارشون شامل هونديون. ({yes} / {no})",
        "appointment_confirmed": "توهان جي ملاقات {doctor} سان {date_time} تي تصديق ٿيل آهي. حوالو ID: {reference}.",
        "report_sent": "توهان جي ڪلينڪل رپورٽ {doctor} کي موڪلي وئي آهي.",
        "cancellation_prompt": "ڇا توهان {doctor} سان {date_time} تي پنهنجي ملاقات منسوخ ڪرڻ چاهيو ٿا؟ ({yes} / {no})",
        "cancellation_confirmed": "توهان جي ملاقات {doctor} سان {date_time} تي منسوخ ٿيل آهي.",
        "reschedule_prompt": "ڇا توهان {doctor} سان پنهنجي ملاقات ٻيهر شيڊول ڪرڻ چاهيو ٿا؟ ({yes} / {no})",
        "slot_error": "اهو ملاقات وقت هاڻي موجود نه آهي. مهرباني ڪري ڪو ٻيو اختيار چونڊيو.",
        "selection_error": "مون اهو انتخاب نه سمجھيو. مهرباني ڪري ڏيکاريل آپشنز مان هڪ کي چونڊيو."
    },
    "doi": {
        "department_booking_prompt": "की तुसीं {department} के डाक्टर नाल नियुक्ति बुक करना चाहोगे? ({yes} / {no})",
        "booking_prompt": "की मैं तुहाडे लिए उपलब्ध नियुक्ति दे स्लॉट्स दा पता लगावा? ({yes} / {no})",
        "report_forward_prompt": "की मैं तुहाडी पूरी क्लिनिकल रिपोर्ट {doctor} नूॅ तुहाडी नियुक्ति तो पहले फॉरवर्ड कर देवां? इस दे विच असाँ चर्चा कीती लक्षण, पैटर्न्स, ट्रिगर्स, अते सिफारिशां शामल हुन्दियां. ({yes} / {no})",
        "appointment_confirmed": "तुहाडी नियुक्ति {doctor} नाल {date_time} लई कंफर्म हो गई है. रेफरेंस ID: {reference}.",
        "report_sent": "तुहाडी क्लिनिकल रिपोर्ट {doctor} नूॅ भेजी गई है.",
        "cancellation_prompt": "की तुसीं {date_time} नूॅ {doctor} नाल अपनी नियुक्ति रद्द करना चाहोगे? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} नाल तुहाडी {date_time} दी नियुक्ति रद्द कर दी गई है.",
        "reschedule_prompt": "की तुसीं {doctor} नाल अपनी नियुक्ति नवा शेड्यूल करना चाहोगे? ({yes} / {no})",
        "slot_error": "ओ नियुक्ति स्लॉट होणहार उपलब्ध नहीं है. कृपया कोई होर स्लॉट चुने.",
        "selection_error": "मैं उस चयन दा समझ नहीं आया. कृपया दिखाए गे विकल्पां विच्चों कोई एक चुने."
    },
    "ks": {
        "department_booking_prompt": "کیا آپ کسی {department} ڈاکٹر کے ساتھ ملاقات کا وقت بک کرنا چاہیں گے؟ ({yes} / {no})",
        "booking_prompt": "کیا آپ چاہتے ہیں کہ میں آپ کے لئے دستیاب ملاقات کے اوقات تلاش کروں؟ ({yes} / {no})",
        "report_forward_prompt": "کیا میں آپ کی تفصیلی طبی رپورٹ {doctor} کو آپ کی ملاقات سے پہلے بھیج دوں؟ اس میں وہ علامات، نمونے، محرکات، اور سفارشات شامل ہوں گی جو ہم نے زیر بحث لائیں۔ ({yes} / {no})",
        "appointment_confirmed": "آپ کی ملاقات {doctor} کے ساتھ {date_time} پر طے پا گئی ہے۔ حوالہ ID: {reference}.",
        "report_sent": "آپ کی طبی رپورٹ {doctor} کو ارسال کردی گئی ہے۔",
        "cancellation_prompt": "کیا آپ {date_time} پر {doctor} کے ساتھ اپنی ملاقات منسوخ کرنا چاہتے ہیں؟ ({yes} / {no})",
        "cancellation_confirmed": "آپ کی ملاقات {date_time} پر {doctor} کے ساتھ منسوخ کر دی گئی ہے۔",
        "reschedule_prompt": "کیا آپ {doctor} کے ساتھ اپنی ملاقات کو دوبارہ طے کرنا چاہیں گے؟ ({yes} / {no})",
        "slot_error": "یہ ملاقات کا وقت اب دستیاب نہیں ہے۔ براہ کرم دوسرا وقت منتخب کریں۔",
        "selection_error": "میں آپ کی اس انتخاب کو سمجھ نہیں سکا۔ براہ کرم دی گئی اختیارات میں سے ایک کا انتخاب کریں۔"
    },
    "mni": {
        "department_booking_prompt": "নাকজার {department} ডাক্তারঢী য়ানং আনবা পালারৌব? ({yes} / {no})",
        "booking_prompt": "নাকজার কন্দিনবা লাক্ষিং ঠিক্পসু কারিগী থম্বিয়ুং পালারৌব? ({yes} / {no})",
        "report_forward_prompt": "াআদুং নাকজার বাহাড়া থোয়কপা শিবুমডা ফাউংদোকটো {doctor} থোক্কহোল টুং। আকোবা য়ারা শিনাই আমা, হৌনগী থরাম, তােমস্পীদা থোয়ৈ আমগী তুসুং ফৌকসি। ({yes} / {no})",
        "appointment_confirmed": "নাকজার {doctor} লা {date_time} থো দোসুং য়ানি। থুমবা হংঙং আইডি: {reference}.",
        "report_sent": "নাকজার বাহাড়া য়ারা থোত্তযালা (ডাক্তার) খোমবা থোকই।",
        "cancellation_prompt": "নাকজার কন্দিনবা তাইবা {date_time} লা {doctor} টুঙানং ঠিক্পসুয়া হল্ব (্লংদ্রোপিহে {yes} / {no}).",
        "cancellation_confirmed": "নাকজার তাকসুম {date_time} লা {doctor} আছিল্ম লাম্ব।",
        "reschedule_prompt": "নাকজার স্থাযিস্টা মিটিং মেন্ডিরু (কিছু) {doctor} লারৌব? ({yes} / {no})",
        "slot_error": "নাগত থাওরোকপনবা মাযিপি থোকসিংরা। অনীং লাক্ষিং লারয়।",
        "selection_error": "নাকজার থোরাককংড়া মুনবাক ইউনিনং পমরু। অফৎμαι মঈংদ্ব পংফাউরারৌব।"
    },
    "sa": {
        "department_booking_prompt": "किं भवतः {department} चिकित्सकेन सह नियुक्तिं एव बुकुमिच्छति? ({yes} / {no})",
        "booking_prompt": "किं अहं अहते उपलब्धाः नियुक्तिः समयः अन्वेष्टुं इच्छति? ({yes} / {no})",
        "report_forward_prompt": "आदिं अहं भवतः विस्तृतं चिकित्सकीय प्रतिवेदनं {doctor} चिकित्सकाय नियुक्तेः पूर्वं प्रेषयेत? अत्र अस्माभिः चर्चां कृतानि लक्षणानि, प्रतिरूपाणि, उद्दीपनानि च सिफारिशः च अन्तर्भवन्ति। ({yes} / {no})",
        "appointment_confirmed": "भवतः नियुक्तिः {doctor} चिकित्सकेन सह {date_time} समये निश्चितः अस्ति। संदर्भ ID: {reference}.",
        "report_sent": "भवतः चिकित्सकीय प्रतिवेदनं {doctor} चिकित्सकाय प्रेषितम् अस्ति।",
        "cancellation_prompt": "किं भवतः {doctor} चिकित्सकेन {date_time} समये नियुक्तिः रद्धुमिच्छति? ({yes} / {no})",
        "cancellation_confirmed": "भवतः नियुक्तिः {doctor} चिकित्सकेन {date_time} समये रद्धा कृतम्।",
        "reschedule_prompt": "किं भवतः {doctor} चिकित्सकेन नियुक्तिं पुनः निर्धातुमिच्छति? ({yes} / {no})",
        "slot_error": "सः नियुक्तिः स्लॉट अब उपलब्धः नास्ति। कृपया अन्यं स्लॉटं चयनं करोतु।",
        "selection_error": "अहं तं चयनं न अवगन्तुं शक्नोमि। कृपया प्रदर्शितस्य विकल्पानां मध्ये एकं चयनं करोतु।"
    },
    "sat": {
        "department_booking_prompt": "ᱥᱮ {department} ᱠᱮ ᱢᱟᱦ ᱠᱟᱛᱤᱭᱟᱜᱟ ᱡᱤᱯᱱᱟᱵᱮ? ({yes} / {no})",
        "booking_prompt": "ᱮᱱᱴᱢᱚ ᱡᱤᱛᱱᱤ ᱢᱟᱦ ᱥᱠᱻᱭᱟᱹ ᱭᱮᱦᱤ? ({yes} / {no})",
        "report_forward_prompt": "ᱮᱞᱟᱹ ᱰᱚᱛ ᱴᱤᱯᱤᱱᱟᱜᱟ {doctor} ᱟ ᱨᱚᱯᱟᱲᱤ ᱢᱟᱦ ᱛᱟᱠᱟᱜᱟ ᱢᱮ ᱠᱟᱭᱟᱢᱮ ᱭᱮᱦᱤ? ᱨᱮᱪᱴᱟᱝ ᱢᱟᱨᱮ ᱡᱚᱲᱤᱭᱟᱜᱟ ᱢᱟᱦ ᱞᱟᱠᱴᱟᱱ ᱠᱚᱲᱟᱹᱞᱟᱹ ᱨᱟᱜᱟ ᱠᱚᱹᱨ ᱱᱚᱨᱚᱠᱟᱜᱽ ᱴᱚᱵᱚ ᱠᱷᱚᱭ ᱴᱷᱟᱞᱴᱮᱥᱟ ᱟᱹᱭᱮ ᱯᱟᱣᱮᱥᱵᱮᱭᱮ। ({yes} / {no})",
        "appointment_confirmed": "ᱮᱱᱴᱢᱚᱥ ᱰᱚ {doctor} ᱟ ᱨᱚᱯᱟᱲᱤ ᱟᱠᱴᱚ {date_time} ᱠᱚ ᱠᱦᱟᱲᱟᱜ ᱾ ᱥᱮᱩᱢᱩ ᱧᱟᱞ: {reference}",
        "report_sent": "ᱮᱱᱴᱢ᱖ᱡᱟᱦᱟᱝᱣᱽᱫᱚ {doctor} ᱟ ᱫᱮᱢᱟᱦᱟ ᱡᱤᱛᱱᱟᱞᱤ ᱢᱷᱟᱢ ᱫᱮ ᱥᱟᱹᱴᱮ ᱢᱦ ᱚ ᱡᱚᱡᱩ।",
        "cancellation_prompt": "ᱮᱱᱴᱢᱚ ᱡᱤᱯᱟᱭᱮᱟᱱ ᱟᱜ {doctor} ᱛᱧ  {date_time} ᱥᱩᱢ ᱢᱟᱦ ᱡᱤᱯᱱᱟᱜᱽ? ({yes} / {no})",
        "cancellation_confirmed": "ᱮᱱᱴᱢᱚ ᱡᱤᱯᱢᱤᱱ {doctor} ᱟᱹᱜᱟ {date_time} ᱟ ᱠᱚᱹ ᱞᱚᱨ ᱜᱟᱭ ᱮᱞᱚ",
        "reschedule_prompt": "ᱮᱞᱚᱯ ᱬᱮᱢᱟᱫ ᱨᱚᱵᱟᱯ ᱡᱤᱯᱱᱟᱜᱽ {doctor} ᱟ? ({yes} / {no})",
        "slot_error": "ᱡᱟᱞ ᱯᱟᱫᱫᱮᱭᱮᱠᱷᱚᱢ ᱡᱮᱥᱝᱤᱭ ᱣᱟᱠᱫ ᱠᱚ ᱜᱟᱠᱴᱤᱯ ᱢᱮᱯᱟᱦᱤ ᱯᱟᱣ ᱞᱢᱟᱞ ᱠᱚᱲ।",
        "selection_error": "ᱮᱱᱴᱢᱚ ᱛᱟᱝ ᱠᱚᱞ ᱢᱟᱯ ᱠᱷᱷ ᱭᱚ। ᱟᱵ ᱡᱮᱥ ᱟᱯᱲᱮᱭ ᱯᱟᱣᱮᱫᱟ ᱞᱟᱷᱟᱢᱹ ᱟᱜ ᱠᱚᱲ।"
    }
})
FULL_WORKFLOW_MESSAGES.update({
    "ne": {
        "department_booking_prompt": "के तपाईं {department} चिकित्सकसँग भेट घाटको समय लिन चाहनुहुन्छ? ({yes} / {no})",
        "booking_prompt": "के म तपाईंको लागि उपलब्ध भेट घाटको समय खोज्न चाहन्छु? ({yes} / {no})",
        "report_forward_prompt": "तपाईंको भेट घाटको अघि {doctor} लाई तपाईंको विस्तृत क्लिनिकल रिपोर्ट पठाउनुपर्छ? यसमा हामीले चर्चा गरेका लक्षणहरू, पैटर्नहरू, ट्रिगरहरू र सिफारिशहरू समावेश हुनेछ। ({yes} / {no})",
        "appointment_confirmed": "{doctor} सँगको तपाईंको भेट {date_time} मा पक्का भएको छ। सन्दर्भ आईडी: {reference}।",
        "report_sent": "{doctor} लाई तपाईंको क्लिनिकल रिपोर्ट पठाइयो।",
        "cancellation_prompt": "के तपाईं {doctor} सँगको {date_time} मा भएको भेट रद्द गर्न चाहनुहुन्छ? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} सँगको {date_time} मा भएको तपाईंको भेट रद्द भएको छ।",
        "reschedule_prompt": "के तपाईं {doctor} सँगको भेट फेरि तय गर्न चाहनुहुन्छ? ({yes} / {no})",
        "slot_error": "त्यो भेटको समय अब उपलब्ध छैन। कृपया अर्को समय छान्नुहोस्।",
        "selection_error": "मैले त्यो चयन बुझ्न सकिन। प्रस्तावित विकल्पहरू मध्ये एक चयन गर्नुहोस्।"
    },
    "sd": {
        "department_booking_prompt": "ڇا توهان {department} ڊاڪٽر سان ملاقات جو وقت وٺڻ چاهيو ٿا؟ ({yes} / {no})",
        "booking_prompt": "ڇا مان توهان لاءِ دستياب ملاقات جا وقت ڳولان؟ ({yes} / {no})",
        "report_forward_prompt": "ڇا مان توهان جي تفصيلي ڪلينڪل رپورٽ {doctor} کي ملاقات کان اڳ موڪلياني چاهيو ٿا؟ انهيءَ ۾ اسان ڳالهايل علامتون، نمونا، ٽرگر ۽ سفارشون شامل ٿينديون۔ ({yes} / {no})",
        "appointment_confirmed": "{doctor} سان توهان جي ملاقات {date_time} تي تصديق ٿي وئي آهي۔ حواله نمبر: {reference}۔",
        "report_sent": "{doctor} کي توهان جي ڪلينڪل رپورٽ موڪلي وئي آهي۔",
        "cancellation_prompt": "ڇا توهان {doctor} سان {date_time} تي ٿيل ملاقات منسوخ ڪرڻ چاهيو ٿا؟ ({yes} / {no})",
        "cancellation_confirmed": "{doctor} سان {date_time} تي ٿيل توهان جي ملاقات منسوخ ڪئي وئي آهي۔",
        "reschedule_prompt": "ڇا توهان {doctor} سان ملاقات جو وقت ٻيهر مقرر ڪرڻ چاهيو ٿا؟ ({yes} / {no})",
        "slot_error": "اهو ملاقات جو وقت هاڻي موجود ناهي۔ ٻيو وقت چونڊيو۔",
        "selection_error": "اهو انتخاب سمجهي نه سگهيس۔ مهرباني ڪري ڏيکاريل آپشنز مان هڪ چونڊيو۔"
    },
    "brx": {
        "department_booking_prompt": "{department} डाक्टरोसिदि अपोइन्तमेन्ट फां जानोनाइबेनि? ({yes} / {no})",
        "booking_prompt": "आङनि फां साबभ इंटरनेट दिमा अपोइन्तमेन्ट खोनोगोनाबेनि? ({yes} / {no})",
        "report_forward_prompt": "आङ {doctor} नाइ अपोइन्तमेन्ट माजिन फाय साउर रिपोर्ट सुनाथांगो जाने? थैमाव आनलागैन समय होबाजि, गाथांग, फाफानिफे बर साइथाधिर सिफरिश फां हा होय। ({yes} / {no})",
        "appointment_confirmed": "{doctor} नाइ आपनि अपोइन्तमेन्ट {date_time} फां पुरापुतो होबो। Reference ID: {reference}।",
        "report_sent": "{doctor} नाइ फां साउर रिपोर्टर फानाबो।",
        "cancellation_prompt": "आङ {doctor} नाइ {date_time} फां होमन्गा अपोइन्तमेन्ट Race भासाजानैबोनि? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} नाइ {date_time} फां होमन्गा आपनि अपोइन्तमेन्ट Race भासाजायालानी।",
        "reschedule_prompt": "आङ {doctor} नाइ अपोइन्तमेन्ट फां मां आउसोंग फां जानैरोजानाइबेनि? ({yes} / {no})",
        "slot_error": "थाि अपोइन्तमेन्ट समय न थांन बाओ थांगुं। फौलारी समय फां जोनो।",
        "selection_error": "आङ थाइ सलेक्सियान बोज़ानाइ। फौलारी आप्शन फां धंगलो।"
    },
    "doi": {
        "department_booking_prompt": "क्या तुसीं {department} डॉक्टर नाल अपॉइन्टमेंट बुक करना चावदे हो? ({yes} / {no})",
        "booking_prompt": "तुस्सीं लेई मैनू उपलब्ध अपॉइन्टमेंट स्लॉट्स लबण देता जाव? ({yes} / {no})",
        "report_forward_prompt": "क्या मैं तुहाडा पूरी क्लिनिकल रिपोर्ट {doctor} नू अपॉइन्टमेंट दे पश्चात फ़ार्वर्ड करदा? इक रिपोर्ट विच साडे मॅचल, पैटर्न, ट्रिगर्स अते सिफारिशां सम्मलित हण। ({yes} / {no})",
        "appointment_confirmed": "तुआडा {doctor} दे नाल अपॉइन्टमेंट {date_time} नू पक्का होया है। Reference ID: {reference}।",
        "report_sent": "{doctor} नू तुहाडा क्लिनिकल रिपोर्ट भेजी गई है।",
        "cancellation_prompt": "की तुसीं {doctor} नाल {date_time} उत्ते अपॉइन्टमेंट रद करना चावदे हो? ({yes} / {no})",
        "cancellation_confirmed": "तुहाडा {doctor} दे नाल {date_time} उत्ते अपॉइन्टमेंट रद हो चुका है।",
        "reschedule_prompt": "क्या तुसीं {doctor} दे नाल अपॉइन्टमेंटनु दुबारा शेड्यूल करना चावंदे हो? ({yes} / {no})",
        "slot_error": "ओ अपॉइन्टमेंट स्लॉट हुण उपलब्ध नहीं। कृपया होर स्लॉट चूनो।",
        "selection_error": "मै वो हाजिर आप्शन समझ नहीं सका। कृपया दिखाए गे ऑप्शन दे विच्चों कोई एक चुनो।"
    },
    "ks": {
        "department_booking_prompt": "کیا آپ {department} ڈاکٹر کے ساتھ ملاقات طے کرنا چاہتے ہیں؟ ({yes} / {no})",
        "booking_prompt": "کیا میں آپ کے لئے دستیاب ملاقاتوں کے وقتوں کو تلاش کروں؟ ({yes} / {no})",
        "report_forward_prompt": "کیا میں {doctor} کو ملاقات سے پہلے آپ کی تفصیلی کلینکل رپورٹ بھیجوں؟ اس میں ہم نے جو علامات، نمونے، محرکات، اور تجاویز پر بات کی ہے وہ شامل ہوں گی۔ ({yes} / {no})",
        "appointment_confirmed": "آپ کی ملاقات {doctor} کے ساتھ {date_time} پر تصدیق شدہ ہے۔ حوالہ نمبر: {reference}۔",
        "report_sent": "آپ کی کلینکل رپورٹ {doctor} کو بھیج دی گئی ہے۔",
        "cancellation_prompt": "کیا آپ {doctor} کے ساتھ {date_time} پر ملاقات کو منسوخ کرنا چاہتے ہیں؟ ({yes} / {no})",
        "cancellation_confirmed": "آپ کی {doctor} کے ساتھ {date_time} پر ملاقات منسوخ کر دی گئی ہے۔",
        "reschedule_prompt": "کیا آپ {doctor} کے ساتھ ملاقات کو دوبارہ طے کرنا چاہتے ہیں؟ ({yes} / {no})",
        "slot_error": "وہ ملاقات وقت اب دستیاب نہیں ہے۔ براہ کرم دوسرا وقت منتخب کریں۔",
        "selection_error": "میں اس انتخاب کو سمجھ نہیں پایا۔ براہ کرم دکھائے گئے اختیارات میں سے ایک کا انتخاب کریں۔"
    },
    "mni": {
        "department_booking_prompt": "ꯈꯤꯏꯇꯝ ꯃꯛꯇꯝ ꯆꯨꯖꯝꯕꯂꯤꯦ {department} ꯗꯤꯀꯀꯂꯥ ꯁꯦꯡ ꯑꯅꯨ꯭ꯐꯥ ꯍꯥꯔꯠ ꯍꯧꯖꯀꯨꯅ ꯄꯨꯡꯇꯦꯡꯒꯤ ꯑꯗꯨꯡꯗꯥ ꯑꯍꯠꯅꯥꯈꯤꯡꯗꯦ ꯇꯨꯒꯅꯤꯗꯦ? ({yes} / {no})",
        "booking_prompt": "ꯀꯦ ꯃꯃꯦ ꯁꯨꯏꯋꯤꯐꯥ ꯇꯔꯅ ꯐꯣꯡꯗꯦ ꯑꯦꯗꯣꯜꯁꯦꯝ ꯍꯥꯔꯡ ꯊꯧꯗꯦꯟꯅꯥꯈꯤꯡꯗꯦ ꯇꯨꯒꯅꯤꯗꯦ? ({yes} / {no})",
        "report_forward_prompt": "ꯃꯊꯡꯅꯥ ꯇꯨꯝꯕꯣ ꯊꯨꯞ ꯒꯥ ꯗꯤꯄꯂꯤꯦ ꯁꯦꯩꯔꯕꯥ ꯗꯧꯐꯤꯕꯦ ꯍꯧꯖꯤꯟꯏ ꯗꯤꯀꯠ {doctor} ꯃꯇꯤ꯫ ꯟꯟꯡꯅꯤꯌꯤꯗꯦ ꯑꯄꯜꯇꯨꯣ ꯁꯤꯔꯦꯔꯕꯠ ꯗꯦ ꯑꯒꯥꯢ ꯃꯐꯥ ꯁꯟꯄ ꯃꯇꯝꯅꯥꯈꯤꯡꯖꯧꯪ ꯊꯧꯗꯦꯅꯥꯈꯤꯡꯕꯤ ꯃꯐ ꯑꯃꯆꯠꯅꯥꯈꯤꯡꯗꯦ? ({yes} / {no})",
        "appointment_confirmed": "{doctor} ꯃꯦꯡ ꯑꯃꯗꯩ ꯆ ꯍꯥꯒ {date_time} ꯀꯅꯢ ꯑꯍꯠꯔꯤꯔꯟꯀꯤꯅꯟ ꯂꯧꯝꯕꯠ ꯄꯧꯅꯤꯤꯝ: {reference}।",
        "report_sent": "{doctor} ꯢ ꯈꯧꯖꯒ ꯎꯌꯤꯃ ꯏꯅꯠ ꯀꯣꯛꯔ ꯁꯨꯔꯄꯕ ꯂꯧꯝꯕꯠ ꯄꯧꯅꯤꯡꯅꯤꯔꯦ ꯑꯍꯦ।",
        "cancellation_prompt": "ꯂꯟꯒ ꯌꯦꯆ, {doctor} ꯃꯦꯡ ꯅꯤꯟ {date_time} ꯂꯁꯥꯡ ꯆ ꯑꯂꯝ ꯄꯥꯡꯖ incarnationreplace ({yes} / {no})",
        "cancellation_confirmed": "{doctor} ꯈꯪ ꯡꯎ꯰ {date_time} ꯈꯪ {department} ꯂꯦ ꯃꯈꯦꯂꯣꯔꯠ ꯊꯥꯕꯗꯥ꯫",
        "reschedule_prompt": "ꯂꯟꯒ ꯌꯦꯆ, {doctor} ꯃ날천ꯁꯦꯇ꯭ ꯗ둴둟 ꯇꯦ꯭ ꯌ데ꯌꯂ ꯂठꯣ꯰ ꯢђꯏꯀ꯭ {yes} / {no})",
        "slot_error": "ꯍꯦꯄꯤꯍꯦꯗꯂꯈꯥꯈꯤꯞ ꯃꯁꯁꯒꯣꯁꯦ ꯈꯥꯑꯍꯠꯢꯗꯤꯀꯤꯒꯦ ꯌꯦꯦꯝꯒꯅꯦ ꯆꯨꯢꯠ",
        "selection_error": "ꯑꯣꯁ ufgava install醫 :cगी",
        "incorrect_format": "that appointment gives incorrect or not full-format present",
        "array_empty": "Published according to make, the object said",
        "api_warning": "Message(thesaurus) welcomes to these positions of that clause must retire by analysis with JSON frame",
        "js_collation": "those import so for ticket or other these behaviour to accept need state like these",
        "option_mismatch": "Sher(have paint name), must point looking couldn't expand",
        "image_para": "Return only step",
        "exact_decimal": "Optioning operations class have but",
        "undefined_item": "check s'dict please solution harder settle",
        "extraneous_quotes": "true or known with introduced an degree",
        "converted_val_copied": "to observe a object quoted along surroundings are < 1 is introducer",
        "placeholder_collate": "lag public objects others include scalar",
        "reasoning_warning": "a pad of function waiting by forward variables marked indicator",
        "field_dict_type": "future targeting further readable standard -1 lowering "
    },
    "sa": {
        "department_booking_prompt": "किं त्वं {department} चिकित्सकसङ्ग अपॉइन्मेंटं स्वीकारुमिच्छसि? ({yes} / {no})",
        "booking_prompt": "किं अहं उपलभ्य अपॉइन्मेंट् समयान् ते सहायालयुं शक्नोमि? ({yes} / {no})",
        "report_forward_prompt": "किं अहं तव विस्तृतं चिकित्सारोपणं प्रतिवेदनं {doctor} इत्यस्मै पूर्वमपॉइन्मेंटप्रतिगन्तव्यम? तस्यामस्मिन्समुदायोल्गनां तेषां लक्षणं, प्रयोजकं, निर्देशं च विचारितमस्तीति। ({yes} / {no})",
        "appointment_confirmed": "{date_time} अस्मिन्ते {doctor} इत्यस्मिन्च चिकित्सकसङ्गे अपॉइन्मेंट् निश्चिनोतमस्ति। सन्दर्भं ID: {reference}।",
        "report_sent": "{doctor} इत्यस्मिन्ते चिकित्सारोपणं प्रतिवेदनं पठानं गतमस्ति।",
        "cancellation_prompt": "किं त्वं {doctor} इत्यस्मिन्ते {date_time} चिकित्सारोपणं अपॉइन्मेंटं विरचितुमिच्छसि? ({yes} / {no})",
        "cancellation_confirmed": "{doctor} इत्यस्मिन्त {date_time} चिकित्सकसङ्गे अपॉइन्मेंट् परित्यक्तमस्ति।",
        "reschedule_prompt": "किं त्वं {doctor} इत्यस्मिन्ते चिकित्सारोपणं अपॉइन्मेंटं पुनर्नियोजयायलुं शक्नोसि? ({yes} / {no})",
        "slot_error": "सः अपॉइन्मेंट् समयः इदानीं उपलब्धः नास्ति। अन्यम् समयं चयनं कृत्तिति।",
        "selection_error": "इदं निर्वाचनं न समझं। प्रदर्शितं विकल्पानां केनापकिं चयनं कृत्तिति।"
    },
    "sat": {
        "department_booking_prompt": "(मेठ) {department} डॉकडॉर जिथे कार्य जाने आहु? ({yes} / {no})",
        "booking_prompt": "अमि याह करनु तनि जाबो हो? ({yes} / {no})",
        "report_forward_prompt": "अमि {doctor} तका य  याय भेंट यभक्षि भेजो हो? ({yes} / {no})",
        "appointment_confirmed": "{date_time} जाय राई अंतयियर {doctor} आइ भेंट जाय हाया। Reference ID: {reference}।",
        "report_sent": "{doctor} को तम किलिन्दी कारण तांकपत्रों भेजो।",
        "cancellation_prompt": "{doctor} को तम नेकसा {date_time} में भेंट में एवंआगमी का चाहाले हो? ({yes} / {no})",
        "cancellation_confirmed": "तुम अक्षर भेंट {doctor} {date_time} उहिं आनं लढ़ाते।",
        "reschedule_prompt": "{doctor} को तम नेकसा पुनः भेंटस्था दो एवंआ आगमी का चाहाले हो? ({yes} / {no})",
        "slot_error": "एताएसय जे भेंट मर्ता उपलाबद ना होइते। कृपया अन्य मर्ता चेही करो। clections",
        "selection_error": "अबयष्य चे ने। परिपर्च कीडकु अन्य किनी सेठ सेधाओ।"
    }
})
